#!/usr/bin/env python3
r"""Build a C++ harness around the REAL CXmlWriter::WriteStringXML.

Nothing here is retyped. Every function under test is cut out of the shipping
source by brace matching:

    core/OOXML/Binary/Presentation/XmlWriter.cpp   CXmlWriter::WriteStringXML
    core/OOXML/Base/Unit.cpp                      XmlUtils::replace_all
                                                  XmlUtils::IsUnicodeSymbol
                                                  XmlUtils::EncodeXmlString

The pre-fix WriteStringXML calls replace_all and the post-fix one calls
EncodeXmlString, so both of its possible dependencies are extracted from real
source either way and the same harness compiles against both revisions.

The only stub is the sink. In the product `m_oWriter` is an
NSStringUtils::CStringBuilder and the call under test is
`m_oWriter.WriteString(s)`, which is

    void CStringBuilder::WriteString(const std::wstring& sString)
    { this->WriteString(sString.c_str(), sString.length()); }

i.e. a plain append of the whole string - see
core/DesktopEditor/common/StringBuilder.cpp. Appending to a std::wstring is
that behaviour exactly, with no truncation or filtering of its own, so the
stub cannot mask or manufacture the defect.

  BASELINE=1 (optionally BASE_REF=<rev>) re-reads both files from git instead
  of the working tree, where the test must FAIL.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CORE = os.path.normpath(os.path.join(HERE, '..', '..', 'core'))
WRITER = 'OOXML/Binary/Presentation/XmlWriter.cpp'
UNIT = 'OOXML/Base/Unit.cpp'
# Pinned to the commit this fix landed on top of. It must NOT default to HEAD:
# once the fix is committed, HEAD carries it, the baseline stops differing and
# the test quietly becomes toothless while still reporting success.
BASE_REF = os.environ.get('BASE_REF', '4a3252194b5649147db5f792a62933fa1a8c4ef9')
BASELINE = bool(os.environ.get('BASELINE'))


def source(rel):
    if BASELINE:
        return subprocess.run(['git', '-C', CORE, 'show', '%s:%s' % (BASE_REF, rel)],
                              capture_output=True, text=True, check=True).stdout
    with open(os.path.join(CORE, rel), encoding='utf-8') as fh:
        return fh.read()


def extract(text, signature, where):
    """Return signature + body, cut out by counting braces."""
    start = text.find(signature)
    if start < 0:
        raise SystemExit('%s: signature not found: %s' % (where, signature))
    if text.find(signature, start + 1) >= 0:
        raise SystemExit('%s: signature is not unique: %s' % (where, signature))
    open_brace = text.index('{', start + len(signature))
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
    raise SystemExit('%s: unbalanced braces in %s' % (where, signature))


writer_src = source(WRITER)
unit_src = source(UNIT)

write_string_xml = extract(
    writer_src, 'void CXmlWriter::WriteStringXML(std::wstring strValue)', WRITER)
replace_all = extract(
    unit_src,
    'void replace_all(std::wstring& subject, const std::wstring& search, const std::wstring& replace)',
    UNIT)
is_unicode_symbol = extract(
    unit_src, 'bool IsUnicodeSymbol( unsigned int symbol )', UNIT)
encode_xml_string = extract(
    unit_src,
    'std::wstring EncodeXmlString(const std::wstring& data, bool bDeleteNoUnicode)',
    UNIT)

sys.stderr.write('extracted from %s:\n  WriteStringXML (%d bytes)\n'
                 % ('git ' + BASE_REF if BASELINE else 'working tree',
                    len(write_string_xml)))

TEMPLATE = r'''// GENERATED by extract.py - do not edit. Every function below the stub is
// verbatim shipping source, cut out by brace matching.
#include <string>
#include <cstdio>
#include <vector>

namespace XmlUtils
{
//@REPLACE_ALL@
//@IS_UNICODE_SYMBOL@
	std::wstring EncodeXmlString(const std::wstring& data, bool bDeleteNoUnicode = true);
//@ENCODE_XML_STRING@
}

namespace NSBinPptxRW
{
	// Stub sink. See the module docstring: CStringBuilder::WriteString appends
	// the whole string, which is what this does.
	struct StubBuilder
	{
		std::wstring data;
		void WriteString(const std::wstring& s) { data += s; }
	};

	class CXmlWriter
	{
	public:
		StubBuilder m_oWriter;
		void WriteStringXML(std::wstring strValue);
	};

//@WRITE_STRING_XML@
}

// ---------------------------------------------------------------------------
// XML 1.0 Char production, https://www.w3.org/TR/xml/#charsets
//   Char ::= #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
// Anything outside this cannot appear in an XML document in any form: there is
// no entity or numeric reference that makes it legal.
static bool isXmlChar(unsigned int c)
{
	return c == 0x9 || c == 0xA || c == 0xD
		|| (c >= 0x20 && c <= 0xD7FF)
		|| (c >= 0xE000 && c <= 0xFFFD)
		|| (c >= 0x10000 && c <= 0x10FFFF);
}

static int g_failures = 0;

static void fail(const char* what, const char* detail)
{
	std::printf("  FAIL  %s: %s\n", what, detail);
	++g_failures;
}

// Append one Unicode scalar the way the product would hold it: a single
// wchar_t where wchar_t is 32 bit, a surrogate pair where it is 16 bit.
static void appendCode(std::wstring& s, unsigned int cp)
{
	if (sizeof(wchar_t) >= 4 || cp <= 0xFFFF)
	{
		s += (wchar_t)cp;
		return;
	}
	cp -= 0x10000;
	s += (wchar_t)(0xD800 + (cp >> 10));
	s += (wchar_t)(0xDC00 + (cp & 0x3FF));
}

static std::wstring writeIt(const std::wstring& in)
{
	NSBinPptxRW::CXmlWriter w;
	w.WriteStringXML(in);
	return w.m_oWriter.data;
}

struct Case { const char* name; unsigned int code; };

int main()
{
	// The characters the reporter of ONLYOFFICE/DesktopEditors#139 pasted, plus
	// the rest of the class they belong to. None of these may reach the output.
	const Case illegal[] = {
		{ "U+0000",              0x0000 },
		{ "U+0008 backspace",    0x0008 },
		{ "U+000B vertical tab", 0x000B },
		{ "U+000C form feed",    0x000C },
		{ "U+001C file sep",     0x001C },
		{ "U+001F unit sep",     0x001F },
		{ "U+FFFE noncharacter", 0xFFFE },
		{ "U+FFFF noncharacter", 0xFFFF },
	};

	std::printf("illegal characters must not reach the slide XML\n");
	for (size_t i = 0; i < sizeof(illegal) / sizeof(illegal[0]); ++i)
	{
		std::wstring in = L"HEAD";
		appendCode(in, illegal[i].code);
		in += L"TAIL";
		std::wstring out = writeIt(in);

		bool clean = true;
		for (size_t j = 0; j < out.size(); ++j)
		{
			if (!isXmlChar((unsigned int)out[j]))
			{
				char buf[160];
				std::snprintf(buf, sizeof(buf),
					"U+%04X survived into the output at index %u - the slide part "
					"is not well-formed XML and the whole slide is dropped on reopen",
					(unsigned int)out[j], (unsigned int)j);
				fail(illegal[i].name, buf);
				clean = false;
				break;
			}
		}
		// Dropping the character must not take the surrounding text with it.
		if (clean && out.find(L"HEAD") == std::wstring::npos)
			fail(illegal[i].name, "text before the character was lost");
		if (clean && out.find(L"TAIL") == std::wstring::npos)
			fail(illegal[i].name, "text after the character was lost");
		if (clean)
			std::printf("  ok    %s\n", illegal[i].name);
	}

	// A lone surrogate is equally illegal and reaches the writer the same way.
	{
		std::wstring in = L"HEAD";
		in += (wchar_t)0xD83D;
		in += L"TAIL";
		std::wstring out = writeIt(in);
		bool clean = true;
		for (size_t j = 0; j < out.size(); ++j)
		{
			if (!isXmlChar((unsigned int)out[j]))
			{
				fail("lone high surrogate", "an unpaired surrogate reached the output");
				clean = false;
				break;
			}
		}
		if (clean)
			std::printf("  ok    lone high surrogate\n");
	}

	// The other half of the contract: everything legal must still come out
	// intact, entities escaped and astral characters preserved. A writer that
	// passed the block above by deleting its input would fail here.
	std::printf("legal content must be preserved\n");
	{
		std::wstring out = writeIt(L"a&b<c>d\"e'f");
		if (out != L"a&amp;b&lt;c&gt;d&quot;e&apos;f")
			fail("predefined entities", "not escaped as expected");
		else
			std::printf("  ok    predefined entities\n");
	}
	const Case legal[] = {
		{ "U+0009 tab",        0x0009 },
		{ "U+000A line feed",  0x000A },
		{ "U+00E9 e-acute",    0x00E9 },
		{ "U+4E2D CJK",        0x4E2D },
		{ "U+1F600 emoji",     0x1F600 },
		{ "U+20000 CJK ext B", 0x20000 },
		{ "U+10FFFF",          0x10FFFF },
	};
	for (size_t i = 0; i < sizeof(legal) / sizeof(legal[0]); ++i)
	{
		std::wstring expect;
		appendCode(expect, legal[i].code);
		std::wstring in = L"HEAD" + expect + L"TAIL";
		std::wstring out = writeIt(in);
		if (out != in)
			fail(legal[i].name, "a legal character was altered or dropped");
		else
			std::printf("  ok    %s\n", legal[i].name);
	}

	if (g_failures)
	{
		std::printf("\n%d failure(s) - ONLYOFFICE/DesktopEditors#139\n", g_failures);
		return 1;
	}
	std::printf("\nall checks passed\n");
	return 0;
}
'''

for token, body in (('//@REPLACE_ALL@', replace_all),
                    ('//@IS_UNICODE_SYMBOL@', is_unicode_symbol),
                    ('//@ENCODE_XML_STRING@', encode_xml_string),
                    ('//@WRITE_STRING_XML@', write_string_xml)):
    assert token in TEMPLATE, token
    TEMPLATE = TEMPLATE.replace(token, body)

print(TEMPLATE)
